# Generated by Django 4.1 on 2023-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('user_id', models.TextField()),
                ('user_image', models.TextField()),
                ('content_image', models.TextField()),
                ('like_count', models.IntegerField()),
            ],
        ),
    ]
